# -*- coding: utf-8 -*-
"""rainfallData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQNgsbBvYAFkaGoEpgzueOuICjr74QAd
"""

import requests

# Coronavirus API URL
api_url_all = 'https://opendata.cwb.gov.tw/api/v1/rest/datastore/C-B0025-001?Authorization=CWB-85C27F24-8F47-46EE-87F0-232AD8F06609&format=JSON&timeFrom=2021-02-01&timeTo=2021-03-01'

def retrieval_api(api_url):
  response = requests.get(api_url)
  # print('Status Code: ' + str(response.status_code))
  return str(response.json())

location_json = retrieval_api(api_url_all)

print(location_json)

location_json = location_json.replace("\'", "\"")#單引號(')轉換成雙引號(")，否則不能使用json
print(location_json)

import json
location_dic = json.loads(location_json)
print(type(location_dic))
print(location_dic)

for i in range(10):
  country = location_dic['records']['location'][i]['station']
  country_ch =country['stationName']
  country_en = country['stationNameEN']
  for j in range(10):
    data = location_dic['records']['location'][i]['stationObsTimes']['stationObsTime'][j]
    data_date = data['dataDate']
    data_weatherElements = data['weatherElements']['precipitation']
    info='地區:'+country_ch+'('+country_en+')'+'日期:'+data_date+'雨量:'+data_weatherElements
    print(info)